# Generated by Django 3.2.3 on 2021-06-04 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0002_remove_deliveryaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryAddress',
            field=models.ForeignKey(blank=True, db_column='DeliveryAddressID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.deliveryaddress'),
        ),
    ]
