# Generated by Django 3.2.3 on 2021-06-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_order_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='saler_staff',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(db_column='PaymentID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='statusNow',
            field=models.CharField(blank=True, db_column='Status_now', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='member',
            field=models.ForeignKey(db_column='MemberID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentDetail',
            field=models.ForeignKey(db_column='PaymentDetailID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.paymentdetail'),
        ),
    ]
