# Generated by Django 3.2.3 on 2021-06-04 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_auto_20210604_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.ForeignKey(db_column='AddressID', on_delete=django.db.models.deletion.CASCADE, to='mystore.address'),
        ),
    ]
