# Generated by Django 3.2.3 on 2021-06-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_alter_deliveryaddress_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentmethod',
            name='shipment',
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipmentMethod',
            field=models.ForeignKey(blank=True, db_column='ShipmentMethodID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.shipmentmethod'),
        ),
    ]
