# Generated by Django 3.2.3 on 2021-06-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0006_auto_20210604_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address',
            field=models.ForeignKey(db_column='AddressID', on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.address'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, db_column='Time', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(db_column='Price'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipmentMethod',
            field=models.ForeignKey(db_column='ShipmentMethodID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.shipmentmethod'),
        ),
    ]
