# Generated by Django 3.2.3 on 2021-06-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20210604_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(db_column='Price'),
        ),
    ]
