# Generated by Django 3.2.3 on 2021-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount_value',
            field=models.BigIntegerField(db_column='Discount_value'),
        ),
    ]
