# Generated by Django 3.2.3 on 2021-06-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_alter_discount_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='item',
            field=models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='mystore.item'),
        ),
    ]
