# Generated by Django 3.2.3 on 2021-06-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_alter_discount_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentDetail',
            field=models.ForeignKey(blank=True, db_column='PaymentDetailID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.paymentdetail'),
        ),
    ]
