# Generated by Django 3.2.3 on 2021-06-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0011_alter_payment_paymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipper',
            field=models.ForeignKey(blank=True, db_column='ShipperID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.shipper'),
        ),
    ]
