# Generated by Django 3.2.3 on 2021-06-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_alter_shipment_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='fee',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.CASCADE, to='mystore.order'),
        ),
    ]
