# Generated by Django 3.2.3 on 2021-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_auto_20210605_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='customer',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='customer_name',
            field=models.CharField(blank=True, db_column='customer_name', max_length=255, null=True),
        ),
    ]
