# Generated by Django 3.2.3 on 2021-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_auto_20210605_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentmethod',
            name='fee',
            field=models.IntegerField(db_column='Fee'),
        ),
    ]
