# Generated by Django 3.2.3 on 2021-06-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_alter_shipmentmethod_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='liked',
        ),
    ]
