# Generated by Django 3.2.3 on 2021-06-04 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0016_remove_feedback_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='CustomerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.customer'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='item',
            field=models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.CASCADE, to='mystore.item'),
        ),
    ]
