# Generated by Django 3.2.3 on 2021-06-04 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_auto_20210605_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attach',
            field=models.CharField(blank=True, db_column='attach', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='time',
            field=models.DateTimeField(blank=True, db_column='time', default=datetime.datetime.now, null=True),
        ),
    ]
