# Generated by Django 3.2.3 on 2021-06-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0018_auto_20210605_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importproduct',
            name='product',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='mystore.product'),
        ),
    ]
