# Generated by Django 3.2 on 2021-06-18 00:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0019_alter_importproduct_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=255, null=True)),
                ('taxId', models.CharField(blank=True, db_column='taxId', max_length=255, null=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='ExportNote',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('createdDate', models.DateTimeField(blank=True, db_column='created_date', default=datetime.datetime.now)),
                ('warehouseStaff', models.ForeignKey(db_column='WarehouseStaffID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.warehousestaff')),
            ],
            options={
                'db_table': 'export_note',
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_code',
        ),
        migrations.CreateModel(
            name='OrderNote',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, db_column='content', max_length=255, null=True)),
                ('order', models.ForeignKey(db_column='OrderID', on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.order')),
            ],
            options={
                'db_table': 'order_note',
            },
        ),
        migrations.CreateModel(
            name='ExportProduct',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('qty', models.IntegerField(db_column='Qty')),
                ('exportNote', models.ForeignKey(db_column='ExportNoteID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.exportnote')),
                ('product', models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.product')),
            ],
            options={
                'db_table': 'export_product',
            },
        ),
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('path', models.CharField(blank=True, db_column='path', max_length=255, null=True)),
                ('product', models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.product')),
            ],
            options={
                'db_table': 'cover',
            },
        ),
        migrations.AlterField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(db_column='CompanyID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mystore.company'),
        ),
    ]
